"""Final ClinDC and the four ablations reported in the manuscript."""

ABLATIONS = {
    "main_no_id_without_virtual_node": {
        "drug_mode": "structure_kg",
        "disease_mode": "kg_text",
        "fusion": "gated",
        "pair_mode": "symmetric",
        "architecture": "pair_level_multimodal",
        "pair_modalities": ("m", "g"),
        "pair_include_virtual": False,
        "kg_signature_mode": "full",
        "use_evidence_weight": True,
    },
    "clindc_without_morgan": {
        "drug_mode": "kg_only",
        "disease_mode": "kg_text",
        "fusion": "gated",
        "pair_mode": "symmetric",
        "architecture": "pair_level_multimodal",
        "pair_modalities": ("g",),
        "pair_include_virtual": False,
        "kg_signature_mode": "full",
        "use_evidence_weight": True,
    },
    "clindc_without_all_kg": {
        "drug_mode": "structure_kg",
        "disease_mode": "text_only",
        "fusion": "gated",
        "pair_mode": "symmetric",
        "architecture": "pair_level_multimodal",
        "pair_modalities": ("m",),
        "pair_include_virtual": False,
        "kg_signature_mode": "full",
        "use_evidence_weight": True,
    },
    "clindc_disease_kg_only": {
        "drug_mode": "structure_kg",
        "disease_mode": "kg_only",
        "fusion": "gated",
        "pair_mode": "symmetric",
        "architecture": "pair_level_multimodal",
        "pair_modalities": ("m", "g"),
        "pair_include_virtual": False,
        "kg_signature_mode": "full",
        "use_evidence_weight": True,
    },
    "clindc_ordered_bidirectional": {
        "drug_mode": "structure_kg",
        "disease_mode": "kg_text",
        "fusion": "gated",
        "pair_mode": "ordered",
        "architecture": "pair_level_multimodal",
        "pair_modalities": ("m", "g"),
        "pair_representation": "ordered",
        "pair_include_virtual": False,
        "bidirectional_inference": True,
        "kg_signature_mode": "full",
        "use_evidence_weight": True,
    },
}
